2022-05-30 23:26:57,952 INFO    Thread-13 (_run_job):94850 [wandb_setup.py:_flush():75] Loading settings from /home/emili/.config/wandb/settings
2022-05-30 23:26:57,953 INFO    Thread-13 (_run_job):94850 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-05-30 23:26:57,953 INFO    Thread-13 (_run_job):94850 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'api_key': '***REDACTED***', 'entity': 'emilibonet', 'project': 'gar_itw', 'root_dir': '/home/emili/Documents/Universitat/TFG/cv-gender-age-recognition', 'run_id': '2sojbyur', 'sweep_param_path': '/home/emili/Documents/Universitat/TFG/cv-gender-age-recognition/wandb/sweep-wb8v3bhr/config-2sojbyur.yaml', 'sweep_id': 'wb8v3bhr'}
2022-05-30 23:26:57,953 INFO    Thread-13 (_run_job):94850 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'code/models/ours/sweeper.py', 'program': '/home/emili/Documents/Universitat/TFG/cv-gender-age-recognition/code/models/ours/sweeper.py'}
2022-05-30 23:26:57,954 INFO    Thread-13 (_run_job):94850 [wandb_init.py:_log_setup():437] Logging user logs to /home/emili/Documents/Universitat/TFG/cv-gender-age-recognition/wandb/run-20220530_232657-2sojbyur/logs/debug.log
2022-05-30 23:26:57,955 INFO    Thread-13 (_run_job):94850 [wandb_init.py:_log_setup():438] Logging internal logs to /home/emili/Documents/Universitat/TFG/cv-gender-age-recognition/wandb/run-20220530_232657-2sojbyur/logs/debug-internal.log
2022-05-30 23:26:57,955 INFO    Thread-13 (_run_job):94850 [wandb_init.py:init():471] calling init triggers
2022-05-30 23:26:57,956 INFO    Thread-13 (_run_job):94850 [wandb_init.py:init():474] wandb.init called with sweep_config: {'batch_size': 14, 'dropout': 0.4102659815216206, 'lr': 0.1, 'momentum': 0.8582718612524161}
config: {}
2022-05-30 23:26:57,956 INFO    Thread-13 (_run_job):94850 [wandb_init.py:init():524] starting backend
2022-05-30 23:26:57,956 INFO    Thread-13 (_run_job):94850 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-05-30 23:26:57,976 INFO    Thread-13 (_run_job):94850 [backend.py:ensure_launched():217] starting backend process...
2022-05-30 23:26:57,978 INFO    Thread-13 (_run_job):94850 [backend.py:ensure_launched():222] started backend process with pid: 96024
2022-05-30 23:26:57,979 INFO    Thread-13 (_run_job):94850 [wandb_init.py:init():533] backend started and connected
2022-05-30 23:26:57,994 INFO    Thread-13 (_run_job):94850 [wandb_run.py:_config_callback():1131] config_cb None None {'batch_size': 14, 'dropout': 0.4102659815216206, 'lr': 0.1, 'momentum': 0.8582718612524161}
2022-05-30 23:26:57,995 INFO    Thread-13 (_run_job):94850 [wandb_init.py:init():597] updated telemetry
2022-05-30 23:26:58,003 INFO    Thread-13 (_run_job):94850 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-05-30 23:26:59,785 INFO    Thread-13 (_run_job):94850 [wandb_run.py:_on_init():1923] communicating current version
2022-05-30 23:27:00,220 INFO    Thread-13 (_run_job):94850 [wandb_run.py:_on_init():1927] got version response upgrade_message: "wandb version 0.12.17 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-05-30 23:27:00,220 INFO    Thread-13 (_run_job):94850 [wandb_init.py:init():659] starting run threads in backend
2022-05-30 23:27:05,230 INFO    Thread-13 (_run_job):94850 [wandb_run.py:_console_start():1897] atexit reg
2022-05-30 23:27:05,230 INFO    Thread-13 (_run_job):94850 [wandb_run.py:_redirect():1770] redirect: SettingsConsole.REDIRECT
2022-05-30 23:27:05,230 INFO    Thread-13 (_run_job):94850 [wandb_run.py:_redirect():1775] Redirecting console.
2022-05-30 23:27:05,231 ERROR   Thread-13 (_run_job):94850 [wandb_run.py:_redirect():1834] Failed to redirect.
Traceback (most recent call last):
  File "/home/emili/miniconda3/envs/viume/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1827, in _redirect
    out_redir.install()
  File "/home/emili/miniconda3/envs/viume/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/emili/miniconda3/envs/viume/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/home/emili/miniconda3/envs/viume/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/emili/miniconda3/envs/viume/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
2022-05-30 23:27:05,231 INFO    Thread-13 (_run_job):94850 [wandb_init.py:init():684] run started, returning control to user process
2022-05-30 23:27:05,232 INFO    Thread-13 (_run_job):94850 [wandb_config.py:__setitem__():150] config set device = cpu - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7efc0fed0bb0>>
2022-05-30 23:27:05,232 INFO    Thread-13 (_run_job):94850 [wandb_run.py:_config_callback():1131] config_cb device cpu None
2022-05-30 23:27:05,232 INFO    Thread-13 (_run_job):94850 [wandb_config.py:__setitem__():150] config set epochs = 30 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7efc0fed0bb0>>
2022-05-30 23:27:05,232 INFO    Thread-13 (_run_job):94850 [wandb_run.py:_config_callback():1131] config_cb epochs 30 None
2022-05-30 23:28:05,472 INFO    Thread-13 (_run_job):94850 [wandb_watch.py:watch():47] Watching
2022-05-30 23:28:05,570 INFO    MainThread:94850 [wandb_run.py:_atexit_cleanup():1866] got exitcode: 255
2022-05-30 23:28:05,570 INFO    MainThread:94850 [wandb_run.py:_restore():1838] restore
